site_name: Ohio Barn Flower Farm
site_author: Tony Gilkerson
nav:
  - Home: index.md
  - Plans:
    - spring2020/plan.md
  - Info:
    - resources.md
    - etc.md
  - Workflow:
    - workflow/mkdocs.md
    - workflow/squarespace-products.md
  - Crew:
    - crew/README.md
    - crew/getting-started-guide.md
    - crew/issues.md
    - crew/1099.md
    - crew/campus-map.md
  - About: about.md

#theme: readthedocs
theme:
  name: material
